# Generated by Django 3.2.5 on 2021-07-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personId', models.BigAutoField(primary_key=True, serialize=False)),
                ('personName', models.CharField(max_length=256)),
                ('personGender', models.CharField(max_length=256)),
                ('personBloodGroup', models.CharField(max_length=5)),
                ('personBOD', models.DateField()),
                ('personAge', models.CharField(max_length=3)),
                ('personPhoto', models.FileField(upload_to='')),
                ('personPhoneNumber', models.CharField(max_length=10)),
                ('personQualificationType', models.CharField(max_length=10)),
                ('personQualificationName', models.CharField(max_length=256)),
                ('personQualificationInstitutionName', models.CharField(max_length=256)),
                ('personQualificationYearOfPassing', models.CharField(max_length=4)),
                ('personOccupationCategory', models.CharField(max_length=256)),
                ('personOccupationType', models.CharField(max_length=256)),
                ('personOccupationTypeDetail', models.CharField(max_length=256)),
                ('personOccupationName', models.CharField(max_length=256)),
                ('personOccupationPhoneNumber', models.CharField(max_length=10)),
                ('personOccupationAddress', models.CharField(max_length=512)),
                ('personOccupationAddressPincode', models.CharField(max_length=6)),
                ('personOccupationFile', models.FileField(upload_to='')),
                ('personMartialStatus', models.CharField(max_length=256)),
                ('personMartialStatusExtra', models.CharField(max_length=256)),
                ('personOccupationAddressArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.area')),
                ('personOccupationAddressCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personOccupationAddressCity', to='KP_Form.city')),
                ('personOccupationAddressState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personOccupationAddressState', to='KP_Form.state')),
                ('personQualificationInstitutionCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personQualificationInstitutionCity', to='KP_Form.city')),
                ('personQualificationInstitutionState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personQualificationInstitutionState', to='KP_Form.state')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('familyId', models.BigAutoField(primary_key=True, serialize=False)),
                ('familyName', models.CharField(max_length=256)),
                ('familySurname', models.CharField(max_length=256)),
                ('marudharMe', models.CharField(max_length=256)),
                ('residenceAddress', models.TextField(max_length=512)),
                ('residencePincode', models.CharField(max_length=6)),
                ('landlineNumber', models.CharField(blank=True, max_length=10, null=True)),
                ('residenceArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.area')),
                ('residenceCity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.city')),
                ('residenceState', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KP_Form.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KP_Form.city'),
        ),
        migrations.AddField(
            model_name='area',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KP_Form.state'),
        ),
    ]
