# Generated by Django 3.2.5 on 2021-07-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KP_Form', '0002_auto_20210726_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='residenceArea',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='familydetails',
            name='residenceCity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='personOccupationAddressArea',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='personOccupationAddressCity',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='personQualificationInstitutionCity',
            field=models.CharField(max_length=256),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
