# Generated by Django 3.2.5 on 2021-07-27 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KP_Form', '0003_auto_20210727_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('typeId', models.AutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=52)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='personBloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='person',
            name='personGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=256),
        ),
        migrations.CreateModel(
            name='QualificationName',
            fields=[
                ('nameId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('typeName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KP_Form.qualificationtype')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='personQualificationName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.qualificationname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='personQualificationType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KP_Form.qualificationtype'),
        ),
    ]
