# Generated by Django 3.2.5 on 2021-07-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KP_Form', '0004_auto_20210727_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='personMartialStatusExtra',
        ),
        migrations.AlterField(
            model_name='person',
            name='personMartialStatus',
            field=models.CharField(choices=[('Unmarried', 'Unmarried'), ('Engaged', 'Engaged'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=256),
        ),
        migrations.AlterField(
            model_name='person',
            name='personOccupationCategory',
            field=models.CharField(choices=[('Businessman', 'Businessman'), ('Professional', 'Professional'), ('Private Employee', 'Private Employee'), ('Govt Employee', 'Govt Employee'), ('Self Employee', 'Self Employee'), ('Student', 'Student')], max_length=256),
        ),
    ]
